name: Run CI for Release
on: 
  push:
    branches: 
      - master
      - release_workflow
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push image
        run: |
          docker build -t ${{secret.DOCKER_REGISTRY}}:digital_cv:${{github.sha}} .
